### ISSUE TITLE
Disable iOS linking?

### ISSUE THREAD

**Issue by nixolas1** [lucienbl/react-native-play-store-in-app-review#1]
Great package, but it gets autolinked to iOS, where it is not needed, and triggers a warning on startup, even if it is not imported in the script.

Module PlayStoreInAppReview requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`.

**Comment by lucienbl** [comment]
Dear @nixolas1 ,

Thank you for reaching out ! I'll fix this now and get back to you as soon as it's done 😊

**Comment by lucienbl** [comment]
Hello @nixolas1 👋 This should be fixed in release 1.0.1. Feel free to re-open this issue if the problem persists with the new version :)

**Comment by nixolas1** [comment]
Nice! I'll test
